### ISSUE TITLE
Caching in Redis

### ISSUE THREAD

**Issue by ArkeologeN** [indexzero/nconf#119]
Well, the package sound's really awesome. I just ended up with the following script:

```javascript
var restify = require('restify'),
        server = restify.createServer({
          name: "Witness API",
          version: '1.0.0'
        }),
        mongoose = require('mongoose'),
        _ = require('lodash'),
        Redis = require('redis'),
        env = process.env.NODE_ENV || 'development',
        config = require('nconf'),
        Tokenizer = require('./lib/tokenizer');

    require('nconf-redis');

    config.use('redis', { host: 'localhost', port: 6379, ttl: 60 * 60 * 1000, db: 0 });

    config.env()
        .argv()
        .file({
            file: __dirname + '/config/' + env + '.json'
        });

    console.dir(typeof config);

    config.save(config, function (err) {
        console.log("Saving ...");
        console.log(err);
    });
..........
```

I basically want it to load configuration from my config file (which it does well) and then save that configuration to `Redis` (so that I can globally access config outside of application)

The above snippet throws this:
```
 return callback(new Error('`value` to be saved must be an object.'));
           ^
TypeError: undefined is not a function
    at Redis.save (/var/www/witness-api/node_modules/nconf-redis/lib/nconf-redis.js:291:12)
    at saveStore (/var/www/witness-api/node_modules/nconf/lib/nconf/provider.js:463:20)
    at /var/www/witness-api/node_modules/nconf/node_modules/async/lib/async.js:246:13
    at iterate (/var/www/witness-api/node_modules/nconf/node_modules/async/lib/async.js:131:13)
    at Object.async.eachSeries (/var/www/witness-api/node_modules/nconf/node_modules/async/lib/async.js:147:9)
    at Object.async.reduce (/var/www/witness-api/node_modules/nconf/node_modules/async/lib/async.js:245:15)
    at Provider.save (/var/www/witness-api/node_modules/nconf/lib/nconf/provider.js:491:9)
    at /var/www/witness-api/index.js:49:12
    at Object.<anonymous> (/var/www/witness-api/index.js:142:3)
    at Module._compile (module.js:456:26)
```

If I try to remove `config` from arguments of `config.save()` then it still throws error.

However, if I remove whole `config.save` part, then it shows nothing in redis.

Any luck?

**Comment by indexzero** [comment]
Fixed in #186.
