### ISSUE TITLE
Issue trying to use the secure mode

### ISSUE THREAD

**Issue by ifuyivara** [indexzero/nconf#193]
Hello,

I'm trying to use the secure mode on 0.8.2 (on CentOS)

This is what I have in my app.js file:

```javascript
nconf.file({
  file: "local.json",
  secure: {
    secret: 'super-secretzzz-keyzz',
    alg: 'aes-256-ctr'
  }
})
```

I'm getting the following error on start:

> Error: Error parsing your configuration file: [/opt/api/local.json]: Not a string or buffer
>    at File.loadSync (/opt/api/node_modules/nconf/lib/nconf/stores/file.js:153:11)
>    at Provider.add (/opt/api/node_modules/nconf/lib/nconf/provider.js:137:23)
>    at Provider.file (/opt/api/node_modules/nconf/lib/nconf/provider.js:63:15)
>    at Object.<anonymous> (/opt/mgdapi/app.js:12:7)
>    at Module._compile (module.js:435:26)
>    at Object.Module._extensions..js (module.js:442:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:311:12)
>    at Module.require (module.js:366:17)
>    at require (module.js:385:17)

The file exists and if I omit the secure option it works just fine.

Any ideas? Am I using this wrong?
Thanks!

**Comment by hinok** [comment]
nconf 0.8.2
OS X 10.11.3
Node 5.1.0

I got exactly the same problem as @ifuyivara, any updates on this?
