### ISSUE TITLE
parsing error catching

### ISSUE THREAD

**Issue by empierre** [indexzero/nconf#219]
Hello,

  It looks link I cannot catch the parsing error through the following code:

if (fileExists('/etc/mydomoathome/config.json')) {
    nconf.use('file', {file: '/etc/mydomoathome/config.json'}, function (err) {
        if (err) {
            logger.warn("No global conf in /etc/mydomoathome:" + err.message);
            return;
        }
    });

error message:

/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160
21:55:33    throw new Error(&quot;Error parsing your configuration file: [&quot; + this.file + ']: ' + ex.message);
21:55:33    ^
21:55:33 Error: Error parsing your configuration file: [/etc/mydomoathome/config.json]: Unexpected token }
21:55:33     at File.loadSync (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/stores/file.js:160:11)
21:55:33     at Provider.add (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:137:23)
21:55:33     at Provider.use (/usr/share/mydomoathome/app/node_modules/nconf/lib/nconf/provider.js:110:10)

any hint ?

**Comment by empierre** [comment]
after many tests, only try / catch works with nconf parsing errors, can you make it evolve to the asynchronous mode ? 

thanks,
