### ISSUE TITLE
nconf with webpack

### ISSUE THREAD

**Issue by empierre** [indexzero/nconf#244]
Hello,

  Trying to make a usable app, I want to pack it with webconf.

  When launching the result, here is the error:

> fs.js:808
>   return binding.readdir(pathModule._makeLong(path));
>                  ^
> 
> Error: ENOENT: no such file or directory, scandir '//nconf/stores'
>     at Error (native)
>     at Object.fs.readdirSync (fs.js:808:18)
>     at Object.<anonymous> (/home/in/MyDomoAtHome/Builds/all.js:139:28568)
>     at Object.<anonymous> (/home/in/MyDomoAtHome/Builds/all.js:139:28837)
>     at a (/home/in/MyDomoAtHome/Builds/all.js:1:169)
>     at Object.<anonymous> (/home/in/MyDomoAtHome/Builds/all.js:1:26186)
>     at Object.<anonymous> (/home/in/MyDomoAtHome/Builds/all.js:2:11648)
>     at a (/home/in/MyDomoAtHome/Builds/all.js:1:169)
>     at /home/in/MyDomoAtHome/Builds/all.js:1:256
>     at Object.<anonymous> (/home/in/MyDomoAtHome/Builds/all.js:1:261)

`module.exports = {
    context: __dirname,
    entry: './mdah.js',
    target: "node",
    output: {
        path: __dirname + '/Builds',
        filename: 'all.js'
    },
    resolve: {
        extensions: ['', '.js', '.ts']
    },
    module: {
        noParse: /node_modules\/json-schema\/lib\/validate\.js/,
        loaders: [
          {
              test: /\.ts$/,
              loader: 'ts'
          },
          {
              test: /\.json$/,
              loader: "json-loader"
          }
        ]
    },
  node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty'
  }
};
`

**Comment by assisantunes** [comment]
+1

**Comment by wjszxli** [comment]
+1

**Comment by jbreckel** [comment]
see #252
