### ISSUE TITLE
secure-file cannot be read if it was created by nconf: Unexpected token � in JSON at position 0

### ISSUE THREAD

**Issue by yarick123** [indexzero/nconf#309]
Hi,
I have just experienced the following problem. After generating a new secured configuration file by nconf, nconf cannot read this file. Interesting is, that this file is looking good.

Here is output of the attached test script:
```
Q:\test-nconf-encrypt>node test-nconf-encrypt
--- config successfully saved!!
Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\stores\file.js:170
    throw new Error("Error parsing your configuration file: [" + this.file + ']: ' + ex.message);
    ^

Error: Error parsing your configuration file: [nconf-test-conf.json]: Unexpected token � in JSON at position 0
    at exports.File.File.loadSync (Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\stores\file.js:170:11)
    at exports.Provider.Provider.add (Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\provider.js:136:23)
    at exports.Provider.Provider.file (Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\provider.js:63:15)
    at nconfConfigureSecretFile (Q:\test-nconf-encrypt\test-nconf-encrypt.js:38:8)
    at nconf.reset.err (Q:\test-nconf-encrypt\test-nconf-encrypt.js:31:4)
    at Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\provider.js:617:36
    at Q:\test-nconf-encrypt\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (Q:\test-nconf-encrypt\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (Q:\test-nconf-encrypt\node_modules\async\lib\async.js:209:22)
    at exports.Provider.Provider._execute (Q:\test-nconf-encrypt\node_modules\nconf\lib\nconf\provider.js:616:18)
```

Here is the code piece:
```
'use strict';

const fs = require('fs');
const nconf = require('nconf');

const nconfFileToSave = "nconf-test-conf.json";
const secret = '1234567890';

{
	if (fs.existsSync(nconfFileToSave)) {
		fs.unlinkSync(nconfFileToSave);
		console.error(`old config file '${nconfFileToSave}' has been successfully deleted!`);
	}

	nconfConfigureSecretFile();

	nconf.set("A", "B");

	nconf.save(err => {
		if(err) {
			console.error(err);
			return;
		}

		console.info('--- config successfully saved!!')
		nconf.reset(err=>{
			if (err) {
				console.error("cannot reset nconf:", err);
				return;
			}
			nconfConfigureSecretFile();
			console.info('OK, nconf.get("A"):', nconf.get("A"));
		});
	});
}

function nconfConfigureSecretFile() {
	nconf.file('secure-file', {
		file: nconfFileToSave,
		secure: {
			secret: secret,
			alg: 'aes-256-cbc'
		}
	});
}
```

I have attached the test package.

PS: I will look inside, maybe I will be able to provide a fix.
PPS: I use node v8.11.4, nconf 0.10.0

[test-nconf-encrypt.zip](https://github.com/indexzero/nconf/files/2473769/test-nconf-encrypt.zip)

**Comment by yarick123** [comment]
PPPS: generated configuration file nconf-test-conf.json:
```
{
  "A": {
    "alg": "aes-256-cbc",
    "value": "04e14587d4eb9e0d3b779c2b39bb8127"
  }
}
```

**Comment by yarick123** [comment]
if replace aes-256-cbc with aes-256-ctr, everything works, but generates warning "(node:11504) Warning: Use Cipheriv for counter mode of aes-256-ctr".

secure-keys, used by nconf, uses module "cipher", which seems to work incorrectly with algorithm aes-256-cbc.
